services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/../database
    environment:
      PORT: 8000
      DB_PATH: /app/../database/restaurant.db

  customer:
    build: ./frontend-customer
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000

  staff:
    build: ./frontend-staff
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
